### ISSUE TITLE
Support for php 8 attributes

### ISSUE THREAD

**Issue by SherinBloemendaal** [Drenso/PhanExtensions#19]
Hello,

Does this plugin support php 8 attributes? It seems it does not but i might be wrong.

`src/Controller/HomeController.php:9 PhanUnreferencedClass Possibly zero references to class`

```
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/')]
    #[Route('/api')]
    public function index(): Response
    {
        $version = $this->getParameter('app.version');
        $appEnvName = $this->getParameter('app.environment_name');

        return $this->render('login.html.twig', ['version' => $version, 'app_env_name' => $appEnvName]);
    }
}
```

Kind regards,
Sherin

**Comment by bobvandevijver** [comment]
Phan supports attributes natively, so there is no need to support it in the plugin. Are you using a recent version of Phan?

**Comment by SherinBloemendaal** [comment]
Yes, version `5.3.2`

**Comment by bobvandevijver** [comment]
Okay, then it should just work fine. You did not post the full error, but you shouldn't need any of the plugins from this project to get this snippet to work with Phan.

**Comment by SherinBloemendaal** [comment]
Ok thanks!
