### ISSUE TITLE
SymfonyAnnotationPlugin do not like @SuppressWarnings

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [Drenso/PhanExtensions#7]
We use a few SCA Tools to check our symfony project and the SymfonyAnnotationPlugin serves well in reducing the false positives because of Annotations.

We also use PHPMD and their recommendation to silence warnings on a per class or method base looks like that:
```
/**
 * The medication order entity represents the complex
 * cha entity medication order.
 * The entity mostly contains getter and setter.
 *
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 * @SuppressWarnings(PHPMD.TooManyFields)
 */
class MedicationOrderEntity extends AbstractCHAEntity {
}
```

but since we do so, the SymfonyAnnotationPlugin reports the above as

> The classlike \App\Entity\SuppressWarnings annotation is undeclared (generated by DrensoAnnotation plugin)

Is there a way to get them to work nicely together?

**Comment by bobvandevijver** [comment]
Good to hear your enjoying the plugin!

We already have a few exceptions in the `SymfonyAnnotationPlugin` (see [line 42](https://github.com/Drenso/PhanExtensions/blob/master/Plugin/Annotation/SymfonyAnnotationPlugin.php#L42)), to suppress the warnings for the `@Target` & `@Annotation` annotations required by Doctrine to load them correctly.

I think we can add this to particular case to the exceptions. If you create a PR, I will make sure to merge it and create a new release for use!

**Comment by bobvandevijver** [comment]
Fixed in #8, released with [v2.4.2](https://github.com/Drenso/PhanExtensions/releases/tag/v2.4.2)!

**Comment by OwnerOfThisIsle** [comment]
Thx for your effort. 

More than a year later I came back to this. Because the exceptions you mentioned above seem to be the reason that this 
```
<?php

namespace App\Entity\Form\Category\Saps\Annotations;

use Doctrine\Common\Annotations\Annotation;

/**
 * @Annotation
 */
```
leads to 

`Possibly zero references to use statement for classlike/namespace Annotation`

So I wanted to add the question, why are Doctrine Annotations explicitly handled as exceptions?

**Comment by bobvandevijver** [comment]
The general answer would be that if you're using annotations in your Symfony project, you would be using Doctrine for it. It is an assumption we made when creating this plugin for our internal use.

According to [their docs](https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/custom.html) you do not need the explicit import for the `@Annotation` to work. So, I believe that the fix would to simply remove the import, as it is actually unused in your example.

That being noted, we're always open for changes, such as configurable exceptions. You can make a PR for that, but if I recall correctly Phan doesn't support plugin configuration (yet). If so, extending the plugin and overwriting the exceptions would be just as easy.

**Comment by OwnerOfThisIsle** [comment]
Well, oh my. Before you mentioned that, I would have never thought that I just can leave out the use statement.

I got rid of them, thx. No need to change anything in the plugin.
